### ISSUE TITLE
[rule: spaced-comment] shebang errors if followed by import

### ISSUE THREAD

**Issue by olalonde** [babel/babel-eslint#163] opened 2015-08-12 11:08 UTC
So I found out that:

```javascript
#!/usr/bin/env node

import { BlockWorker } from '../Workers';
import config from '../config';
// ...
```

gives a spaced-comment error, while this does not:

```javascript
#!/usr/bin/env node

import config from '../config';
import { BlockWorker } from '../Workers';
// ...
```

See https://github.com/eslint/eslint/issues/3296

**Comment by hzoo** [comment] 2015-08-13 13:55
Ok looks like the issue is because although eslint tries to remove all shebang comments in https://github.com/eslint/eslint/blob/c694db4740d3f8e3d9f908a4e7321c398e924225/lib/eslint.js#L804-L810, babel-eslint has another leadingComments on `spawn`

![screen shot 2015-08-13 at 9 54 44 am](https://cloud.githubusercontent.com/assets/588473/9251469/60d50b22-41a1-11e5-881b-33f559807f52.png)

**Comment by millette** [comment] 2016-04-22 23:09
As a workaround for now, I start my cli files with this instead:
```javascript
#!/usr/bin/env node
let _eslint_workaround = true // eslint-disable-line no-unused-vars
```
Third line can be anything it seems.

Works with the latest standard code style.

**Comment by danez** [comment] 2016-04-25 10:30
There is a PR with the fix for babylon now. Problem was that babylon is cloning the key to the value if destructuring with shorthands are used in objects. Espree/Acorn is not doing any cloning and therefore also not cloning the comment.

**Comment by dasilvacontin** [comment] 2016-04-25 19:59
Thanks for working on the fix @danez! Looking forward to remove my personal workaround from the code:
```js
#!/usr/bin/env node
// @flow
2 + 2 === 5 // https://git.io/vwmJK
import fs from 'fs'
```

**Comment by millette** [comment] 2016-05-07 15:54
Well this is strange. I'm using
```js
  "devDependencies": {
    "ava": "^0.14.0",
    "babel-eslint": "^6.0.4",
    "coveralls": "^2.11.9",
    "nyc": "^6.4.3",
    "standard": "^7.0.1"
  }
```

And it worked for a day or so without the workaround.

After another install, something (not sure what) upgraded babel-types from 6.8.0 to 6.8.1 and it's failing again.

**Comment by danez** [comment] 2016-06-26 20:52
Sorry that it took so long to fix this. As of babylon 6.8.2 this is now fixed.

**Closed by danez** 2016-06-26 20:52 UTC
Labels: babylon, bug

**Comment by dasilvacontin** [comment] 2016-06-26 21:09
Thanks @danez!
