### ISSUE TITLE
Cannot read property of '0' of undefined

### ISSUE THREAD

**Issue by rui-infotrack** [babel/babel-eslint#155] opened 2015-07-27 00:37 UTC
Dear dev:
I met this problem:
```
Module build failed: TypeError: Cannot read property '0' of undefined
    at d:\Source\reveal\node_modules\eslint\lib\eslint.js:676:46
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (d:\Source\reveal\node_modules\eslint\lib\eslin
    at processText (d:\Source\reveal\node_modules\eslint\lib\cli-engine.js:201:27)
    at CLIEngine.executeOnText (d:\Source\reveal\node_modules\eslint\lib\cli-engine.js:361:26
    at lint (d:\Source\reveal\node_modules\eslint-loader\index.js:26:20)
    at Object.module.exports (d:\Source\reveal\node_modules\eslint-loader\index.js:120:7)
```

My source code is very simple:
```javascript
import React, { Component } from 'react';
import App from './containers/App';

class App extends Component {
    render() {
        return (
            <h1>Hello World!</h1>
        );
    }
}

React.render(<App />, document.getElementById('root'));

```

And here's part of my package.json
```json
"devDependencies": {
    "babel-core": "^5.2.16",
    "babel-eslint": "^4.0.0",
    "babel-loader": "^5.3.2",
    "babel-runtime": "^5.7.0",
    "babelify": "^6.0.2",
    "browserify": "^10.0.0",
    "chai": "^1.9.2",
    "css-loader": "^0.15.4",
    "eslint": "^0.24.1",
    "eslint-loader": "^0.14.1",
    "eslint-plugin-react": "^2.7.0",
```

And I use webpack to build.

Looks all normal to me so I'm wondering what's wrong there... Could you help have a look?

Thank you very much!

**Comment by andreijs** [comment] 2015-07-27 00:56
I get the same error while using babylon 5.8.9, downgrading to babylon 5.8.5 was fine for me

**Comment by rui-infotrack** [comment] 2015-07-27 00:59
@andreijs My problem is that exactly same babel-eslint, eslint as well as index.js, one of them works on my home computer, whilst another doesn't work on my working computer. I guess this could be a bug in babel-eslint source...

**Comment by sebmck** [comment] 2015-07-27 01:00
The code provided code snippet doesn't compile. Do you have a complete example?

**Comment by ktei** [comment] 2015-07-27 01:16
@sebmck 
Can you refer to this?

https://github.com/ktei/babeleslint

i'm @rui-infotrack  by the way.

That project I mentioned above gives me `Cannot read property of '0' of undefined`.

If you npm install all the packages and run webpack, it should fail (at least for me)
If you comment out `"parser": "babel-eslint",` in `.eslintrc', then webpack works.

Thank you!

**Comment by sebmck** [comment] 2015-07-27 01:22
Thanks for the repo @ktel. `range` was removed from `babylon` as it wasn't used anywhere but apparently ESLint relies on it so I've shimmed it in. Should be fixed as of `babel-eslint` 4.0.1, thanks! :blush:

**Closed** 2015-07-27 01:21 UTC

**Comment by ktei** [comment] 2015-07-27 01:22
@sebmck Cheers! Thank you man!

**Comment by ash2k** [comment] 2015-07-27 01:40
I'm seeing this issue too. Even with `babel-eslint` v4.0.1.

```
/project/node_modules/eslint/lib/eslint.js:676
                var range = scope.block.range[0];
                                             ^
TypeError: Cannot read property '0' of undefined
    at /project/node_modules/eslint/lib/eslint.js:676:46
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (/project/node_modules/eslint/lib/eslint.js:675:27)
    at processText (/project/node_modules/eslint/lib/cli-engine.js:201:27)
    at processFile (/project/node_modules/eslint/lib/cli-engine.js:226:12)
    at /project/node_modules/eslint/lib/cli-engine.js:322:26
    at /project/node_modules/eslint/lib/util/traverse.js:61:17
    at Array.forEach (native)
    at traverse (/project/node_modules/eslint/lib/util/traverse.js:41:54)
    at /project/node_modules/eslint/lib/util/traverse.js:63:17
```
Babel v5.8.9, eslint v0.24.1.

**Comment by sebmck** [comment] 2015-07-27 01:45
@ash2k Right you are. Missed a couple of places. Fixed via cfe989e11af61e8fafe71ca421d454fdc147b835 and `babel-eslint` 4.0.2

**Comment by ash2k** [comment] 2015-07-27 01:49
@sebmck better with 4.0.2 but now I'm seeing `Cannot set property '0' of undefined` in a couple of places. No stacktrace.

**Comment by sebmck** [comment] 2015-07-27 01:50
@ash2k Can you put together a reproducible example?

**Comment by sebmck** [comment] 2015-07-27 01:51
I've back ported the `range` changes to the 3.x series as 3.1.28 to ensure that users on the old major wont be effected.

**Comment by ash2k** [comment] 2015-07-27 01:54
```javascript
/*eslint no-console:0 no-process-exit:0 */
(function () {
  'use strict';

})();
```
If you remove the top comment it works.

**Comment by sebmck** [comment] 2015-07-27 01:59
`attachComments` was using `range`. Fixed via 435407c1baeb78db758c97bdb87b51b998b6a07c and `babel-eslint` 4.0.3/3.1.29

**Comment by ash2k** [comment] 2015-07-27 02:03
Works for me! Thanks.

**Comment by ash2k** [comment] 2015-07-27 02:07
I don't know if it is related, but the following snippet fails with `A space is required after ','  comma-spacing`:

```javascript
x(1, `template literal string`);

function x() {}
```
`.eslintrc`:
```
parser: babel-eslint
environment:
  node: true
  mocha: true
ecmaFeatures:
  generators: true
  modules: true
  blockBindings: true
  arrowFunctions: true
  destructuring: true
  forOf: true
  templateStrings: true
```

**Comment by sebmck** [comment] 2015-07-27 02:08
@ash2k Shouldn't be related. Mind opening a new issue?

**Comment by ash2k** [comment] 2015-07-27 02:44
@sebmck #156
