### ISSUE TITLE
Breaks prefs.enabled(enabled => enabled && _run())

### ISSUE THREAD

**Issue by kigorw** [babel/babel-eslint#32] opened 2015-03-04 11:29 UTC
It breaks on such code
```
prefs.enabled(enabled => enabled && _run())
```
outout
```
/Users/kigorw/.nvm/v0.10.26/lib/node_modules/eslint/lib/rules/strict.js:33
    for (i = 0; i < statements.length; i++) {
                              ^
TypeError: Cannot read property 'length' of undefined
    at getUseStrictDirectives (/Users/kigorw/.nvm/v0.10.26/lib/node_modules/eslint/lib/rules/strict.js:33:31)
    at EventEmitter.modes.never.FunctionExpression (/Users/kigorw/.nvm/v0.10.26/lib/node_modules/eslint/lib/rules/strict.js:156:20)
    at EventEmitter.emit (events.js:117:20)
    at Controller.controller.traverse.enter (/Users/kigorw/.nvm/v0.10.26/lib/node_modules/eslint/lib/eslint.js:683:25)
    at Controller.__execute (/Users/kigorw/.nvm/v0.10.26/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/kigorw/.nvm/v0.10.26/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/Users/kigorw/.nvm/v0.10.26/lib/node_modules/eslint/lib/eslint.js:676:24)
    at processFile (/Users/kigorw/.nvm/v0.10.26/lib/node_modules/eslint/lib/cli-engine.js:172:23)
    at /Users/kigorw/.nvm/v0.10.26/lib/node_modules/eslint/lib/cli-engine.js:271:26
    at walk (/Users/kigorw/.nvm/v0.10.26/lib/node_modules/eslint/lib/util/traverse.js:81:9)
k:lib kigorw$ eslint app.js
```

**Comment by sebmck** [comment] 2015-03-04 11:31
Duplicate of #20 and #23. Please upgrade.

**Closed by sebmck** 2015-03-04 11:31 UTC
