### ISSUE TITLE
Unused variables in jsx

### ISSUE THREAD

**Issue by mbektimirov** [babel/babel-eslint#110] opened 2015-05-22 13:27 UTC
All variables used in jsx code are marked as unused:
![2015-05-22 18 22 13](https://cloud.githubusercontent.com/assets/918009/7771335/10b789b2-00b0-11e5-8770-ff2ee28211ca.png)

**Comment by sebmck** [comment] 2015-05-22 13:28
Duplicate of #6, #5, #79 etc. As has been said previous, use the rules in [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react). Thanks :smile:

**Closed by sebmck** 2015-05-22 13:28 UTC

**Comment by mbektimirov** [comment] 2015-05-22 13:33
Got it. Thanks for the blazing fast answer :+1:

**Comment by hzoo** [comment] 2015-05-22 14:33
Maybe your bot can check for "jsx unused" here =). Or maybe I should just add something to the readme about react rules
