### ISSUE TITLE
Import component is shown as unused variable

### ISSUE THREAD

**Issue by max-mykhailenko** [babel/babel-eslint#74] opened 2015-04-21 07:46 UTC
![screen shot 2015-04-21 at 10 45 21 am](https://cloud.githubusercontent.com/assets/1213198/7247569/8e17e04c-e813-11e4-9968-9e528cec6f1b.png)

**Comment by sebmck** [comment] 2015-04-21 07:52
Duplicate of #5. Use [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react).

**Closed by sebmck** 2015-04-21 07:52 UTC
