### ISSUE TITLE
sort-vars does not work with destruction when using babel-eslint plugin

### ISSUE THREAD

**Issue by gajus** [babel/babel-eslint#175] opened 2015-08-23 15:46 UTC
To reproduce the issues:

```
git clone https://github.com/gajus/eslint-issue-3474.git
cd eslint-issue-3474
npm install
node ./node_modules/eslint/bin/eslint.js ./index.js
```

which ought to produce:

```
curiosity:gulp-eslint-issue-86 gajus$ ./node_modules/eslint/bin/eslint.js ./index.js
/gulp-eslint-issue-86/node_modules/eslint/lib/rules/sort-vars.js:21
                    var lastVariableName = memo.id.name,
                                               ^
TypeError: Cannot read property 'id' of undefined
    at /gulp-eslint-issue-86/node_modules/eslint/lib/rules/sort-vars.js:21:48
    at Array.reduce (native)
    at EventEmitter.VariableDeclaration (/gulp-eslint-issue-86/node_modules/eslint/lib/rules/sort-vars.js:19:31)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at Controller.controller.traverse.enter (/gulp-eslint-issue-86/node_modules/eslint/lib/eslint.js:824:25)
    at Controller.__execute (/gulp-eslint-issue-86/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/gulp-eslint-issue-86/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/gulp-eslint-issue-86/node_modules/eslint/lib/eslint.js:817:24)
    at processText (/gulp-eslint-issue-86/node_modules/eslint/lib/cli-engine.js:199:27)
```

Related issues have been raised:

* https://github.com/eslint/eslint/issues/3474
* https://github.com/adametry/gulp-eslint/issues/86

**Comment by shinnn** [comment] 2015-08-23 23:06
~~adametry/gulp-eslint#86~~

**Comment by hzoo** [comment] 2015-08-24 01:20
I can reproduce this with the regular eslint parser fine (2.1.0)?

```js
export default class {
    render () {
        let {
            a
        } = this,
            // Presence of variable declaration after destruction causes the error.
            b;
    }
}
```

```yaml
ecmaFeatures:
  modules: true
env:
  es6: true
rules:
    sort-vars: 2
```

I tried with your linked repo and it was failing on eslint 2.1.0/master as well? You need to npm install eslint as well in your package.json.

**Comment by hzoo** [comment] 2015-08-24 13:24
Ok closing since we can all reproduce https://github.com/eslint/eslint/issues/3474#issuecomment-134061958

**Closed by hzoo** 2015-08-24 13:24 UTC
