### ISSUE TITLE
Bug report: Always errors for use strict

### ISSUE THREAD

**Issue by mondwan** [babel/babel-eslint#228] opened 2015-12-31 03:04 UTC
# Versions

    $ cat package.json
      "devDependencies": {
           "eslint": "~1.10.3",
           "babel-eslint": "~5.0.0-beta6",
            "eslint-plugin-react": "~3.13.1"
      }

# .eslintrc

```
$ cat .eslintrc 
{
  "parser": "babel-eslint",
  "env": {
    "browser": true,
    "node": true,
    "amd": true
  },
  "settings": {
      "ecmascript": 6,
      "jsx": true
  },
  "plugins": [
      "react"
  ],
  "rules": {
    "strict": [2, "global"],
  }
}
```

# a.js

```
"use strict";

console.log('a.js');
```

# Reproduce error

```
$ node_modules/.bin/eslint -c .eslintrc a.js 

/home/mondwan/Documents/test/babel_eslint_test/a.js
  3:1  error  Use the global form of "use strict"  strict

✖ 1 problem (1 error, 0 warnings)
```

# Note

* I have tried `"use strict"`, `"use strict";` `'use strict'` and `'use strict';`. None of them work.
* I have tried `Babel-eslint v4.1.6`. No such bug occur

**Comment by jmm** [comment] 2016-01-04 21:35
Thanks for the report! I think this is due to the introduction of the `Directive*` node types in Babel v6. There are probably 2 solutions: persuade `eslint` to modify the rule to check for those node types first, or here rework them to the regular AST structure / types that the `eslint` rule is expecting. BTW, this can be trimmed down to a more minimal reproduction.

**Comment by jmm** [comment] 2016-01-04 22:06
I double checked with eslint on their gitter and per **nzakas** they only want to support ESTree.

**Comment by satya164** [comment] 2016-01-05 18:30
I'm also facing this.

**Comment by hzoo** [comment] 2016-01-05 18:41
We can definitely change directive to estree b/c that's what we've had to do for everything else anyway. If you are using modules you shouldn't need use strict since they are all in strict mode right?

**Comment by satya164** [comment] 2016-01-05 18:46
@hzoo Yeah. My code is a mix of these things right now as I'm running in my tests with Babel and other files with plain Node. I should change to use modules anyways and setup the server to run with babel :D

**Comment by jmm** [comment] 2016-01-05 18:59
@hzoo I was wondering what is [this line](https://github.com/babel/babel-eslint/blob/9230859edcdfd5001c16ea1545800e1c842f0a34/index.js#L432) for?:

```js
ast.directives = ast.program.directives;
```

**Comment by hzoo** [comment] 2016-01-05 22:49
I think I was just trying to copy whatever was needed from the babylon AST to estree since it uses File instead of Program but looking at what you posted I wouldn't need to add that line since estree doesn't use that anyway.

**Comment by jmm** [comment] 2016-01-05 23:06
@hzoo :+1:

**Comment by hzoo** [comment] 2016-01-07 03:05
Ok still have to convert Directive to an ExpressionStatement that has a Literal - It's getting pretty annoying to do this manually. Maybe we can use some more babel utilities to make it easier.

**Comment by mondwan** [comment] 2016-01-07 03:06
Sorry, I am not sure I cannot follow the discussion.

Any hints for `Directive* node`, `AST tree`, `ESTree`? And how should I fix this problem? By configuration ?

**Comment by hzoo** [comment] 2016-01-07 03:08
The AST is different so we have to convert it in https://github.com/babel/acorn-to-esprima/blob/master/src/toAST.js. Not much you can do other than using a different version or not using the rule.

**Comment by mondwan** [comment] 2016-01-07 03:16
Yes. I am using a different version currently. But how to `not using the rule`?

And I am not sure the meaning of `AST` and `esproma`? I guess this is some kind of parsing mechanism? Do you have any links for showing the concept of them?

Thanks very much.

**Comment by hzoo** [comment] 2016-01-07 03:50
Oh I just meant turning off the rule `"strict": [2, "global"],` (although you probably don't want that).

AST: https://en.wikipedia.org/wiki/Abstract_syntax_tree
esprima: http://esprima.org/, https://github.com/jquery/esprima - esprima/babylon/acorn are javascript parsers. Check out http://astexplorer.net/, https://www.youtube.com/watch?v=rKuNbEwoQfQ

You'll just have to wait for a fix.

**Comment by mondwan** [comment] 2016-01-07 05:52
Thanks. I will check them out later on.

**Comment by jmm** [comment] 2016-01-07 13:55
@hzoo
> Ok still have to convert Directive to an ExpressionStatement that has a Literal - It's getting pretty annoying to do this manually. Maybe we can use some more babel utilities to make it easier.

It is a bit annoying, but it shouldn't be *too* bad. Want me to take a crack at it? (I sort of already did it before just to test things out.)

**Comment by jmm** [comment] 2016-01-22 23:19
WIP fix for this: https://github.com/babel/acorn-to-esprima/compare/master...jmm:directives. I believe `acorn-to-esprima` is the correct home for this, right?

**Comment by hzoo** [comment] 2016-01-22 23:24
Yeah. Also, all that code needs cleanup - would be nice to be able to use more babel methods instead of stuff [like](https://github.com/jmm/acorn-to-esprima/blob/b4ab065f868b611a70c3b85c0e020ae22aa88a60/src/toAST.js#L121)

**Comment by d6u** [comment] 2016-01-29 03:48
FYI, `strict: [2, 'function']` behaves like what `strict: [2, 'global']` intended to do.

**Comment by jmm** [comment] 2016-01-30 13:52
@hzoo Thanks.
> would be nice to be able to use more babel methods instead of stuff like

Hmm, I probably don't actually know the Babel method for that as of yet.

Submitted https://github.com/babel/babel-eslint/pull/241 for this.

@d6u I'm not sure what you mean.

**Closed** 2016-01-30 14:22 UTC

**Comment by jmm** [comment] 2016-01-30 14:35
Huh, so putting "Fixes {{someuser}}/{{somerepo}}#123" in a PR in a different repo closes the referenced issue when merged? Maybe just if they're under the same org?

**Comment by hzoo** [comment] 2016-01-30 14:46
Yeah since you have colloborator access to the org

**Comment by jmm** [comment] 2016-01-30 14:52
Oh ok, I'll have to be more careful with that. But since you merged and published https://github.com/babel/acorn-to-esprima/pull/5 it is fixed now :sparkles:.

**Comment by hzoo** [comment] 2016-01-30 16:36
Fixed with https://github.com/babel/babel-eslint/releases/tag/v5.0.0-beta7
