### ISSUE TITLE
Mixed babel versions through babel-eslint@8 throw error during processing indent in template strings.

### ISSUE THREAD

**Issue by swernerx** [babel/babel-eslint#585] opened 2018-01-31 06:56 UTC
Sorry for the long title. I have a tough time getting it any shorter. I am currently experience an issue where two of my projects don't work together well anymore. The reason seems to be that the current version of babel-eslint is based on the beta version of babel while my babel preset is being based on v7. 

That's the error I am seeing:

```
> eslint error.js 
Cannot read property 'range' of null
TypeError: Cannot read property 'range' of null
    at OffsetStorage.setDesiredOffset (/Users/swerner/Workspace/test/node_modules/eslint/lib/rules/indent.js:335:45)
    at TemplateLiteral.node.expressions.forEach (/Users/swerner/Workspace/test/node_modules/eslint/lib/rules/indent.js:1306:29)
    at Array.forEach (<anonymous>)
    at Object.TemplateLiteral [as listener] (/Users/swerner/Workspace/test/node_modules/eslint/lib/rules/indent.js:1300:34)
    at Program:exit.listenerCallQueue.filter.forEach.nodeInfo (/Users/swerner/Workspace/test/node_modules/eslint/lib/rules/indent.js:1475:55)
    at Array.forEach (<anonymous>)
    at Program:exit (/Users/swerner/Workspace/test/node_modules/eslint/lib/rules/indent.js:1475:26)
    at listeners.(anonymous function).forEach.listener (/Users/swerner/Workspace/test/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/swerner/Workspace/test/node_modules/eslint/lib/util/safe-emitter.js:47:38)
```

The checked file looks trivially simple:

```
var x = {
  foo: `${any}thing`
}
```

My eslint configuration just extends the preset:

```yaml
extends:
  - readable
```

When I force switch to babel-eslint@7.2.3 everything works fine again:

<img width="880" alt="works-with-old-version" src="https://user-images.githubusercontent.com/145201/35608903-802e4bd8-065b-11e8-91a0-99b3d3cb85fd.png">

I inspected the code in `indent.js` inside `eslint`s code base and it seems where with the old version there is a `TemplateLiteral` there is passed `null` to `setDesiredOffset()` when using the new version.

This is the content of my `package.json`:

```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "babel-preset-edge": "^1.5.1",
    "eslint-config-readable": "^1.7.0"
  }
}
```

I am not sure what happens here. It seems `eslint`s code does not protect against `null` values but this might be okay as it worked before. 

I am wondering about what people deeper in the babel eco system are thinking of this.

**Comment by swernerx** [comment] 2018-01-31 06:58
Versions used: npm@5.6.0 + node@9.4.0

**Comment by swernerx** [comment] 2018-01-31 07:15
I downgraded `babel-eslint` in the new minor version of `eslint-config-readable` and now it works again flawlessly:

```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "babel-preset-edge": "^1.5.1",
    "eslint-config-readable": "^1.8.0"
  }
}
```

**Comment by jacargentina** [comment] 2018-03-02 18:39
@swernerx same problem, but doing a little research, i 've found at least on my case, that it works just by going back to version `8.2.1`; the offending version is `8.2.2`

**Comment by jsg2021** [comment] 2018-03-15 21:02
Linking the same issue from eslint. (They seem to agree its a babel-eslint issue)
https://github.com/eslint/eslint/issues/10043

**Comment by jsg2021** [comment] 2018-03-23 07:05
Seems fixed with 8.2.2 and eslint 4.19.0

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jsg2021** [comment] 2018-03-27 04:47
make sure you’re using eslint from within your node_modules, not global. also make sure your node_modules are in a good clean state. (delete them, and package lock and reinstall)

**Comment by Tom910** [comment] 2018-05-22 07:16
Some problem and babel still in beta version

**Comment by yyynnn** [comment] 2018-06-15 10:18
Same problem with 8.2.2 and 4.19.1 with stylelint

**Comment by kaicataldo** [comment] 2018-06-15 20:21
Dupe of https://github.com/babel/babel-eslint/issues/530

**Comment by kaicataldo** [comment] 2018-06-15 20:21
Closing this in favor of the other issue.

**Closed by kaicataldo** 2018-06-15 20:21 UTC
