### ISSUE TITLE
no-unused-vars, no-undef errors in simple ES6 class / react example

### ISSUE THREAD

**Issue by chmanie** [babel/babel-eslint#21] opened 2015-03-01 19:51 UTC
index_es6.js (using the react 0.13 syntax)
``` javascript
'use strict';

import React from 'react';

class HelloMessage extends React.Component {
  render() {
    return <div>Hello {this.props.name}</div>;
  }
}

React.render(<HelloMessage name="Sebastian" />, document.body);
```

eslint output (using eslint-babel):

```
index_es6.js
   5:6   error  HelloMessage is defined but never used  no-unused-vars
  11:14  error  'HelloMessage' is not defined           no-undef
```

index_es5.js
``` javascript
'use strict';

var React = require('react');

var HelloMessage = React.createClass({
	render: function () {
		return <div>Hello {this.props.name}</div>;
	}
});

React.render(<HelloMessage name="Sebastian" />, document.body);
```

eslint output (using eslint-babel):
```
src/app/index_old.js
  11:14  error  'HelloMessage' is not defined  no-undef
```

Is this an issue or am I doing something stupid here?

**Comment by RnbWd** [comment] 2015-03-02 01:02
I'm getting that error for all classes

**Comment by RnbWd** [comment] 2015-03-02 01:56
specifically classes are not-defined - I haven't tried using with React yet.

**Comment by WRidder** [comment] 2015-03-02 19:45
+1 Got the same errors regarding "defined but never used"

**Comment by spicydonuts** [comment] 2015-03-04 19:59
Also having this problem.  I have a module that exports a class (`export default class SomeClass`) and a utility module that individually exports named functions (`export function someHelper...`).  It doesn't like either one.

**Comment by gaearon** [comment] 2015-03-06 12:50
This seems to dupe #https://github.com/babel/babel-eslint/issues/21.

**Comment by sebmck** [comment] 2015-04-14 01:07
Can you please verify that this issue still exists on 3.0.1?

**Comment by jerrysu** [comment] 2015-04-14 01:45
I'm still seeing this with `babel-eslint`@3.0.1.

However, when using `eslint-plugin-react` with `babel-eslint`, I don't have these issues any longer.

**Comment by mridgway** [comment] 2015-04-16 04:56
Confirmed still seeing this issue with `babel-eslint@3.0.1` and `eslint@0.19.0`.

**Comment by cemckinley** [comment] 2015-04-16 23:10
I am also seeing this issue with `babel-eslint@3.0.1` and `eslint@0.19.0`. Looks like this also came up before with eslint but was fixed there: https://github.com/eslint/eslint/issues/1534

**Comment by grahamb** [comment] 2015-05-08 17:21
Similar to @cemckinley, I'm seeing this with `babel-eslint@3.1.1` and `eslint@0.20.0`.

```
'use strict';

import React from 'react';
import Router from 'react-router';
import CreateSpace from 'apps/CreateSpace';
import MySpaces from 'apps/MySpaces';
import SpaceDirectory from 'apps/SpaceDirectory';

const { Route, NotFoundRoute, DefaultRoute, Link, RouteHandler } = Router;

if (__DEV__) {
  require('../scss/dev.scss');
}

const App = React.createClass({
  render() {
    return (
      <RouteHandler />
    );
  }
});

const NotFound = React.createClass({
  render() {
    const divstyle = {
      textAlign: 'center',
      paddingTop: '35px'
    };

    const imgstyle = {
      width: '25%'
    };

    return (
      <div style={divstyle}>
        <img style={imgstyle} src="/images/sadpanda.svg" alt="The panda is sad because it couldn't find the page you wanted" />
        <h2>Page Not Found</h2>
        <p>Oops, we couldn't find that page.</p>
      </div>
    );
  }
});

const route_base_path = __DEV__ ? '/' : '/canvasspaces';
const routes = (
  <Route name="app" path={route_base_path} handler={App}>
    <Route name="create_space" handler={CreateSpace} />
    <Route name="my_spaces" handler={MySpaces} />
    <Route name="space_directory" handler={SpaceDirectory} />
    <DefaultRoute handler={MySpaces} />
    <NotFoundRoute handler={NotFound}/>
  </Route>
);

Router.run(routes, Router.HistoryLocation, (Handler) => {
  React.render(<Handler/>, document.getElementById('CanvasSpacesApp'));
});

export default App;
```

```src/js/index.js
   9:8   error  Route is defined but never used          no-unused-vars
   9:15  error  NotFoundRoute is defined but never used  no-unused-vars
   9:30  error  DefaultRoute is defined but never used   no-unused-vars
   9:44  error  Link is defined but never used           no-unused-vars
   9:50  error  RouteHandler is defined but never used   no-unused-vars
  55:44  error  Handler is defined but never used        no-unused-vars

✖ 6 problems (6 errors, 0 warnings)
```

**Comment by RnbWd** [comment] 2015-05-09 02:02
> However, when using eslint-plugin-react with babel-eslint, I don't have these issues any longer.

eh? is that a solution? I stopped noticing the errors when I included the react-plugin, but haven't worked on anything this week.

**Comment by sebmck** [comment] 2015-05-09 02:05
Yup, it's the solution. Use the [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react) rules if you're using JSX. It can't really be fixed on the `babel-eslint` side.

**Closed by sebmck** 2015-05-09 02:05 UTC

**Comment by steve918** [comment] 2015-09-04 06:34
It seems the eslint react plugin fixes this error, but it exists outside of react projects.

Something as simple as

    class Item {
      constructor() {
        this.id = 0;
      }
    }

Will produce this error, it doesn't have to extend a React component.  Pulling in the eslint react plugin to solve the issue when I'm not using react seems like a lazy work around.

**Comment by hzoo** [comment] 2015-09-04 13:18
Can you reproduce with the regular parser, maybe an eslint issue. But, if you export the class it should be fixed.

**Comment by tjwebb** [comment] 2016-05-23 03:12
I'm running into this issue with a regular ES6 class.

**Comment by jesusreal** [comment] 2016-05-23 06:27
Yes, me too. I am using the class only in the ReactDOM.render() method. I wonder if this bug was reintroduced in the last upgrade. For the time being I had to disable the "no-unused-vars" rule.

**Comment by danez** [comment] 2016-05-23 08:29
Can one of you please open a new bug with an example and the according eslintrc file. Thanks.

**Comment by jesusreal** [comment] 2016-05-31 19:54
Hi, sorry for not answering before, I will do it :)

**Comment by jesusreal** [comment] 2016-05-31 20:57
I investigated the bug and it seems to be an eslint issue. I still have the same problem if I use:
`parserOptions: {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
        "jsx": true
    }
},`
instead of:
`parser: 'babel-eslint',`

**Comment by jesusreal** [comment] 2016-05-31 21:49
In case it can help someone, my issue was resolved here: https://github.com/eslint/eslint/issues/6303
