### ISSUE TITLE
eslint crashes with error at no-unused-vars.js:121

### ISSUE THREAD

**Issue by istarkov** [babel/babel-eslint#81] opened 2015-04-28 20:41 UTC
It crashes on such property initializers 
```javascript
export class CatalogPageRightBlockContentNew {
  iWillCrashEsLint = (i) => {
    return this.props.catalog_results && this.props.catalog_results.get(i);
  }
}
```
with error 
```
/usr/local/lib/node_modules/eslint/lib/rules/no-unused-vars.js:121
                if (type === "Parameter" && def.node.parent.type === "Property
                                                           ^
TypeError: Cannot read property 'type' of undefined
    at getUnusedLocals (/usr/local/lib/node_modules/eslint/lib/rules/no-unused-vars.js:121:60)
    at Array.map (native)
    at getUnusedLocals (/usr/local/lib/node_modules/eslint/lib/rules/no-unused-vars.js:141:58)
    at Array.map (native)
    at getUnusedLocals (/usr/local/lib/node_modules/eslint/lib/rules/no-unused-vars.js:141:58)
    at Array.map (native)
    at getUnusedLocals (/usr/local/lib/node_modules/eslint/lib/rules/no-unused-vars.js:141:58)
    at Array.map (native)
    at getUnusedLocals (/usr/local/lib/node_modules/eslint/lib/rules/no-unused-vars.js:141:58)
    at EventEmitter.Program:exit (/usr/local/lib/node_modules/eslint/lib/rules/no-unused-vars.js:147:26)
```

.eslintrc 
```
{
    "parser": "babel-eslint",

    "env": {
        "browser": true,
        "node": true,
        "es6": true
    },

    "ecmaFeatures": {
        "jsx": true,
    },

    "rules": {
        "strict": 2,
        "semi": 2,
        "quotes": [2, "single"],
        "no-multi-spaces": 0,
        "camelcase": 0,
        "comma-dangle": 0,
        "no-trailing-spaces": 0,
        "no-spaced-func": 0,
        "no-unused-expressions": 0,
        "no-unused-vars": 2,
        "new-cap": 0,

        "no-underscore-dangle": 0,
        "no-use-before-define": [0, "nofunc"],

    }
}
```

**Comment by b2whats** [comment] 2015-05-06 12:15
+1

**Comment by istarkov** [comment] 2015-05-06 12:35
Looks like this issue is duplicate of https://github.com/babel/babel-eslint/issues/71

**Comment by sebmck** [comment] 2015-05-07 12:48
Yep, duplicate of #71.

**Closed by sebmck** 2015-05-07 12:48 UTC
