### ISSUE TITLE
npm-registry description "codded"

### ISSUE THREAD

**Issue by alundiak** [babel/babel-eslint#259] opened 2016-02-19 02:07 UTC
<img width="897" alt="screenshot 2016-02-19 03 06 15" src="https://cloud.githubusercontent.com/assets/2131633/13164473/d9578922-d6b5-11e5-819c-c55fd2f6dec3.png">

**Comment by kaicataldo** [comment] 2016-03-08 00:37
Is this caused by the Travis build status badge being on the same line as the title?

**Comment by hzoo** [comment] 2016-03-08 01:43
Totally possible - want to make a PR? :smile:

**Comment by kaicataldo** [comment] 2016-03-08 03:25
Sure, haha. How do we test that it works on the npm site though?

**Comment by hzoo** [comment] 2016-03-08 03:27
We just update it and see (not a big deal to test and moving it to the next line doesn't matter much)

If we don't want to do that, then we just use a different project and test it (acutally we can just use https://github.com/hzoo/hzoo-npm-publish haha)

**Comment by kaicataldo** [comment] 2016-03-08 03:39
Let's see if that fixes it :smile:

**Closed** 2016-03-08 04:09 UTC
Labels: help wanted
