### ISSUE TITLE
Upgrading to 11.0.0-beta.0 from 8.2.6 causes another linter plugin to start failing

### ISSUE THREAD

**Issue by kaiyoma** [babel/babel-eslint#745] opened 2019-01-26 00:39 UTC
We have a linter plugin (written/published internally) that checks for unnecessary blank lines in our source files. For the purposes of this issue, it's relevant that this plugin prohibits blank lines before the import statements at the top of a file, except when the first line is a comment. In that case, a blank line between the comment and the first import statement is acceptable.

This plugin is passing, but if I upgrade to the latest beta version of babel-eslint, it starts failing, saying that blank lines are not allowed above import blocks. I haven't dug into this, but I'm guessing that somehow the (first line) comments are disappearing. Does babel-eslint somehow modify the files being linted?

**Comment by kaicataldo** [comment] 2019-01-28 01:21
It’s hard to tell without looking at the rule source code or knowing what exactly the error is. One thing that comes to mind: comment attachment was removed in babel-eslint v11 (ESLint core hasn’t used comment attachment since v4). Are you relying on `leadingComments` for either the Program or first ImportDeclaration nodes by any chance?

**Comment by kaiyoma** [comment] 2019-01-28 19:09
Yes, we are using `leadingComments` in the code for our plugin.

**Comment by kaicataldo** [comment] 2019-01-28 19:23
Okay, this is working as intended then. Please see https://eslint.org/docs/user-guide/migrating-to-4.0.0#-ast-nodes-no-longer-have-comment-properties  for how to upgrade the plugin.

**Comment by hzoo** [comment] 2019-02-01 17:35
Ok closed as intended change

**Closed by hzoo** 2019-02-01 17:35 UTC
