### ISSUE TITLE
Comma in template strings triggers `comma-spacing`

### ISSUE THREAD

**Issue by pascalduez** [babel/babel-eslint#43] opened 2015-03-09 16:17 UTC
```js
`${foo}, ${bar}`;
```
```
0:0  error  A space is required after ','  comma-spacing
```

**Comment by sebmck** [comment] 2015-03-09 16:18
Duplicate of #31.

**Closed by sebmck** 2015-03-09 16:18 UTC

**Comment by pascalduez** [comment] 2015-03-09 16:20
> Duplicate of #31.

Dang! Sorry.
