### ISSUE TITLE
Flow type triggers space-infix-ops error

### ISSUE THREAD

**Issue by gajus** [babel/babel-eslint#226] opened 2015-12-28 23:40 UTC
```js
(foo: string = 'test') => {};
```

I am getting an error:

> space-infix-ops: Infix operators must be spaced.

**Comment by adrienbrault** [comment] 2016-01-21 14:51
Having this issue as well!

**Comment by gajus** [comment] 2016-02-10 12:24
@hzoo Does this issue even fall in the `babel-eslint` domain?

**Comment by hzoo** [comment] 2016-02-10 12:33
Unless babel-eslint is doing something wrong (possible), most likely the rule just doesn't account for flow correctly so you would have to overwrite the rule with the eslint-plugin-babel repo/rules.

**Comment by danez** [comment] 2016-04-25 22:09
This is also reported at eslint/eslint#5211 and they also accept patches now for types.

**Comment by danez** [comment] 2016-07-22 19:20
Fixed in eslint, and will be released probably with next version.

**Comment by OlegZee** [comment] 2016-08-05 09:47
My package references "babel-eslint": "^6.1.2" and I updated eslint to 3.2.2 but still getting the error.
Why this issue is closed?

**Comment by danez** [comment] 2016-08-05 09:50
Because it should have been fixed in eslint 3.2, I'm gonna check

**Comment by OlegZee** [comment] 2016-08-05 09:51
What a great response time?!

**Comment by OlegZee** [comment] 2016-08-05 10:05
@danez 
eslint works fine, the problem is in outdated gulp-eslint task which uses eslint@2.1.0.
Thank you for quick reply and sorry for troubling you.

**Closed** 2016-08-05 10:06 UTC
Labels: bug, eslint

**Comment by emirotin** [comment] 2016-08-06 07:56
I have the same issue with the most recent versions of everything. Minimal repro: https://github.com/emirotin/flow-lint-issue

**Comment by danez** [comment] 2016-08-06 12:04
@emirotin Thanks for making the example repo, I confirmed that polymorphic functions cause this error. Created a new Issue #366
