### ISSUE TITLE
errors if comma-spacing isn't respected in template strings if placeholders are used in it

### ISSUE THREAD

**Issue by bloodyowl** [babel/babel-eslint#80] opened 2015-04-27 17:23 UTC
ref https://github.com/eslint/eslint/issues/2393#issuecomment-96723445

```javascript
const foo = `hello,`

console.log(foo)
```

doesn't error, when

```javascript
const foo = `hello${ 1 + 1 },`

console.log(foo)
```

does error

```
1:28  error  A space is required after ','  comma-spacing
```

**Comment by sebmck** [comment] 2015-04-27 17:23
Duplicate of #31.

**Closed by sebmck** 2015-04-27 17:23 UTC
