### ISSUE TITLE
Error when short-hand fat arrow func used with `"strict": [1, "global"]` rule

### ISSUE THREAD

**Issue by jesstelford** [babel/babel-eslint#23] opened 2015-03-03 06:51 UTC
When I run

```bash
$ ./node_modules/.bin/eslint index.js
```

I get the error:

```bash
$ ./node_modules/.bin/eslint index.js
/dev/node_modules/eslint/lib/rules/strict.js:33
    for (i = 0; i < statements.length; i++) {
                              ^
TypeError: Cannot read property 'length' of undefined
    at getUseStrictDirectives (/dev/node_modules/eslint/lib/rules/strict.js:33:31)
    at EventEmitter.modes.global.FunctionExpression (/dev/node_modules/eslint/lib/rules/strict.js:178:20)
    at EventEmitter.emit (events.js:120:20)
    at Controller.controller.traverse.enter (/dev/node_modules/eslint/lib/eslint.js:683:25)
    at Controller.__execute (/dev/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/dev/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/dev/node_modules/eslint/lib/eslint.js:676:24)
    at processFile (/dev/node_modules/eslint/lib/cli-engine.js:172:23)
    at /dev/node_modules/eslint/lib/cli-engine.js:271:26
    at walk (/dev/node_modules/eslint/lib/util/traverse.js:81:9)
```

`index.js`:

```javascript
'use strict';
var foo = bar => bar.zip;
```

`.eslintrc`:

```json
{
  "parser": "babel-eslint",
  "rules": {
    "strict": [1, "global"]
  }
}
```

`package.json`:

```json
{
  ...
  "dependencies": {
    "babel": "^4.6.5",
    "babel-eslint": "^1.0.12",
    "eslint": "^0.15.1"
  }
}
```

Note that babel correctly understands the shorthand fat arrow syntax when compiling:

```bash
$ ./node_modules/.bin/babel index.js
"use strict";

var foo = function (bar) {
  return bar.zip;
};
```

**Comment by sebmck** [comment] 2015-03-03 06:52
Duplicate of #20.

**Closed by sebmck** 2015-03-03 06:52 UTC
