### ISSUE TITLE
Upgrading from 8.2.6 to 10.0.1 leads to lots of errors: Cannot read property 'range' of null

### ISSUE THREAD

**Issue by kaiyoma** [babel/babel-eslint#741] opened 2019-01-14 21:14 UTC
Node: 10.13.0
eslint: 5.12.0
babel: 7.2.2

If I upgrade from 8.2.6 to 10.0.1 and then run the linter, lots of new errors (in the linter itself) start appearing. They all seem to look like this:

```
TypeError: Cannot read property 'range' of null
    at SourceCode.getTokenBefore (...\node_modules\eslint\lib\token-store\index.js:303:18)
    at checkSpacingBefore (...\node_modules\eslint\lib\rules\template-curly-spacing.js:54:42)
    at TemplateElement (...\node_modules\eslint\lib\rules\template-curly-spacing.js:119:17)
    at listeners.(anonymous function).forEach.listener (...\node_modules\eslint\lib\util\safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (...\node_modules\eslint\lib\util\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (...\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (...\node_modules\eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (...\node_modules\eslint\lib\util\node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (...\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:632:23)
```

I can't tell which files are causing this because that information isn't in the output. Still, I'd like to help out, so let me know if you need more information from me.

**Comment by manavbp** [comment] 2019-01-22 08:47
Hey im having the same issue is there any fix for this?

**Comment by EXio4** [comment] 2019-01-25 13:11
A solution I came up with (which is as hacky as it can be, but hey, don't judge me) - is to regenerate `yarn.lock`(which is just removing it and doing `yarn install` again)

**Comment by kaicataldo** [comment] 2019-01-25 16:09
Does this also occur with the latest prerelease version (11.0.0-beta.0)?

**Comment by barroudjo** [comment] 2019-01-25 17:53
I had the same problem here... ``rm -rf node_modules`` and removing ``package-lock.json`` and ``npm i`` solved it as well.

**Comment by kaiyoma** [comment] 2019-01-25 18:33
The "clean install" approach (blowing away `node_modules`) does not fix the issue for me. I'm pretty sure there's a legitimate bug in the code somewhere.

**Comment by kaiyoma** [comment] 2019-01-25 19:12
@kaicataldo The crash isn't happening in that beta version, so it looks like you guys fixed it, but I'm seeing new (unrelated) issues. Our import order plugin is now getting triggered for some reason, possibly because comments (in the file being linted) are being stripped out. I won't dig into that though until there's an official babel-eslint release.

**Comment by kaicataldo** [comment] 2019-01-25 20:46
@kaiyoma Feel free to make issues. That kind of feedback is what we're looking for with this prerelease. Reading from the end user's config is a pretty big departure from what this project has done in the past.

**Comment by worc** [comment] 2019-02-06 20:05
```
babel-eslint: ^9.0.0
eslint: ^5.13.0
```

i was getting the same range of null issue trying to use this parser, and for whatever reason, deleting node_modules and yarn.lock and then reinstalling dependencies cleared up the issue. i also changed the declared versions from a static to caret style, so maybe there's a small version mismatch in there somewhere which finally got unstuck with that bit of looseness?

**Comment by italoborges** [comment] 2019-03-15 09:06
I had to downgrade to the same version @worc post it. With **babel-eslint** ^10.0.1 wasn't working.

I tried remove **node_modules**, **package-lock.json** and install all dependencies again, didn't work either.

**Comment by noe132** [comment] 2019-07-02 03:09
I have same package-lock.json without lockfile,
using `npm install` to get all dependencies, gets this range of null error,
using `yarn` to get all dependencies, it's all fine

using `eslint@6.0.1` and `babel-eslint@10.0.2`

**Comment by oleblaesing** [comment] 2019-08-29 12:46
I'm facing this problem too and I solved it also by removing `node_modules` and regenerating `yarn.lock`. However regenerating the whole lockfile **shouldn't** be considered a viable choice, because it collides with the concept of a lockfile (and it also breaks my system at other places). Are there any other known solutions to this problem?

**Comment by kaiyoma** [comment] 2019-08-29 15:18
Back when I ran into this, I upgraded to the latest version 11 beta, and that solved this issue. Recently though, I started to run into a different problem with babel-eslint, and searching through issues revealed that dropping back down to version 10 was the solution, so now I'm running 10.0.3 and everything works.

**Comment by upcwangying** [comment] 2019-12-20 03:54
我有同样的问题
```
TypeError: Cannot read property 'range' of null
Occurred while linting E:\AQSC\fe\frontapp-vue-samples\src\store\modules\tpridmp\common\permission.js:7
    at SourceCode.getTokenBefore (E:\AQSC\fe\frontapp-vue-samples\node_modules\eslint\lib\token-store\index.js:303:18)
    at checkSpacingBefore (E:\AQSC\fe\frontapp-vue-samples\node_modules\eslint\lib\rules\template-curly-spacing.js:60:42)
    at TemplateElement (E:\AQSC\fe\frontapp-vue-samples\node_modules\eslint\lib\rules\template-curly-spacing.js:119:17)
    at listeners.(anonymous function).forEach.listener (E:\AQSC\fe\frontapp-vue-samples\node_modules\eslint\lib\util\safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (E:\AQSC\fe\frontapp-vue-samples\node_modules\eslint\lib\util\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (E:\AQSC\fe\frontapp-vue-samples\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (E:\AQSC\fe\frontapp-vue-samples\node_modules\eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (E:\AQSC\fe\frontapp-vue-samples\node_modules\eslint\lib\util\node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (E:\AQSC\fe\frontapp-vue-samples\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:632:23)
Process finished with exit code -1
```

**Comment by fangbinwei** [comment] 2019-12-21 16:48
works for me 
```js
    "rules": {
      "indent": [
        "error",
        2,
        {
          "ignoredNodes": [
            "TemplateLiteral"
          ]
        }
      ],
      "template-curly-spacing": [
        "off"
      ]
    },
```

**Comment by upcwangying** [comment] 2019-12-29 04:22
@fangbinwei  Thanks

**Comment by BlueRaja** [comment] 2020-02-11 23:54
I can confirm this is still an issue with 10.0.3.  Removing `node_modules` or `yarn.lock` does not help.  Upgrading to `11.0.0-beta2` _does_ help, but then you have to use a beta version...

The fix provided by @fangbinwei also works, but then you lose eslint for templates.  Both the `ignoredNodes` and `template-curly-spacing` keys are required; if either one is missing, the error still repros.

**Comment by kaicataldo** [comment] 2020-08-04 00:14
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).

**Closed by kaicataldo** 2020-08-04 00:14 UTC
