### ISSUE TITLE
Error with "export const ..." and space-in-brackets: [2, "always"]

### ISSUE THREAD

**Issue by jeddy3** [babel/babel-eslint#87] opened 2015-05-09 11:06 UTC
Hello,

I've tried to narrow down the cause of the error as much I can. I ended up with...

Given a config of:

```yaml
---
parser: babel-eslint

ecmaFeatures:
  modules: true

# 0: off, 1: warning, 2: error
rules:

  # consistent whitespace in brackets
  space-in-brackets: [2, "always"]
```

And a JavaScript source file of:

```js
export const bar = "foo"
```

I get the following error:

```bash
d:\node\www\stylelint\node_modules\eslint\lib\token-store.js:90
        return tokens[starts[node.range[0]] - (skip || 0) - 1];
                                 ^
TypeError: Cannot read property 'range' of undefined
    at EventEmitter.api.getTokenBefore (d:\node\www\stylelint\node_modules\eslint\lib\token-store.js:90:34)
    at RuleContext.(anonymous function) [as getTokenBefore] (d:\node\www\stylelint\node_modules\eslint\lib\rule-context.js:84:33)
    at EventEmitter.ExportNamedDeclaration (d:\node\www\stylelint\node_modules\eslint\lib\rules\space-in-brackets.js:248:33)
    at EventEmitter.emit (events.js:129:20)
    at Controller.controller.traverse.enter (d:\node\www\stylelint\node_modules\eslint\lib\eslint.js:726:25)
    at Controller.__execute (d:\node\www\stylelint\node_modules\eslint\node_modules\estraverse\estraverse.js:393:31)
    at Controller.traverse (d:\node\www\stylelint\node_modules\eslint\node_modules\estraverse\estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify (d:\node\www\stylelint\node_modules\eslint\lib\eslint.js:719:24)
    at processFile (d:\node\www\stylelint\node_modules\eslint\lib\cli-engine.js:197:27)
    at d:\node\www\stylelint\node_modules\eslint\lib\cli-engine.js:299:26
```

No don't get an error without `parser: babel-eslint`. So I assume it's something in `babel-eslint` rather than `eslint` itself, but I could be wrong.

System: win32
Node version: 0.12.1

```bash
$ npm list --depth=0
stylelint@0.1.0 d:\node\www\stylelint
├── babel@5.2.17
├── babel-eslint@3.1.1
├── babel-tape-runner@1.1.0
├── eslint@0.20.0
├── postcss@4.1.9
└── tape@4.0.0
```

Any ideas what might be going on either with the module or at my end? Oh, and I understand the module is experimental :)

Thanks!

**Comment by hzoo** [comment] 2015-05-09 13:38
I think it might be an issue from `eslint`?

It's odd that the rule is `space-in-brackets: [2, "always"]` has an error since in the code snippet there aren't any brackets.

If you remove that rule for the `eslintrc` then it works. Also it seems to work in `eslint@0.19.0`. The rule was modified in `eslint@0.20.0` from https://github.com/eslint/eslint/issues/2216

**Comment by nzakas** [comment] 2015-05-09 15:34
If there's no error with the default parser, then it's a compatibility issue with babel-eslint.

**Comment by hzoo** [comment] 2015-05-09 15:42
So I commented out `parser: babel-eslint` to use the default parser and had to add `blockBindings: true` to fix the `unexpected token const` error. So I am getting the same error with the default parser though.

**Comment by nzakas** [comment] 2015-05-09 15:55
You must use `ecmaFeatures` to enable ES6 features in ESLint, that's a feature. If you can reproduce the original error reported in this issue with the default parser and the appropriate `ecmaFeatures` settings, then please file an ESLint bug. Otherwise, it's a compatibility issue with babel-eslint and I can't help you.

**Comment by hzoo** [comment] 2015-05-09 16:02
Alright cool #2471.

**Comment by hzoo** [comment] 2015-05-09 16:39
I ran it again with `eslint#master` and got no errors for both parsers so this should be fixed in the next release of eslint. Fixed in commit: https://github.com/eslint/eslint/commit/3738de8ca8acd746d37c00594e9c163a32337a3f

**Comment by jeddy3** [comment] 2015-05-09 17:58
Thank you for looking into this so quickly! I'll close the issue now.

Thanks again!

**Closed** 2015-05-09 17:59 UTC
