### ISSUE TITLE
Array comprehension [no-undef]

### ISSUE THREAD

**Issue by SimonDegraeve** [babel/babel-eslint#28] opened 2015-03-04 01:32 UTC
From the example in Babel website
```js
// Array comprehensions
var results = [
  for(c of customers)
    if (c.city == "Seattle")
      { name: c.name, age: c.age }
]
```

Error =>
`'c' is not defined. (no-undef);`

Is it on purpose? Am I suppose to declare `c` before the array comprehension (since I cannot do it in the `for`block)? 

Thanks

**Comment by sebmck** [comment] 2015-03-04 01:32
Duplicate of #9.

**Closed by sebmck** 2015-03-04 01:32 UTC

**Comment by SimonDegraeve** [comment] 2015-03-04 01:34
Sorry about that...
