### ISSUE TITLE
error  'App' is not defined  no-undef

### ISSUE THREAD

**Issue by moroshko** [babel/babel-eslint#29] opened 2015-03-04 03:31 UTC
Hi, 

I get the following error:

    var App = React.createClass({
      render: function() {
        return (
          <div>
            <h3>My Component Example</h3>
            <MyComponent />
          </div>
        );
      }
    });

    React.render(<App />, document.getElementById('app'));    // error  'App' is not defined  no-undef

Here is my `.eslintrc` file:

    {
      "env": {
        "node": true,
        "browser": true
      },
      "parser": "babel-eslint",
      "rules": {
        "space-after-keywords": "always",
        "quotes": "single"
      }
    }

I use `babel-loader` to run eslint with WebPack. Here is the relevant bit from `webpack.config.js`:

    module: {
      loaders: [
        { test: /\.js$/, loaders: ["react-hot", "babel-loader", "eslint-loader"], exclude: /node_modules/ }
      ]
    }

What am I doing wrong?

**Comment by sebmck** [comment] 2015-03-04 03:58
> What am I doing wrong?

Nothing, it's a bug.

**Comment by gaearon** [comment] 2015-03-06 12:52
Seems to be a dupe of #8.

**Comment by gaearon** [comment] 2015-03-06 12:52
Nope. Actually it's a dupe of https://github.com/babel/babel-eslint/issues/15.

**Comment by MoOx** [comment] 2015-03-19 13:59
Probably need to check this with eslint 0.17 changes for jsx and react.

**Comment by MoOx** [comment] 2015-03-19 14:08
I am not having the issue anymore with eslint 0.17 and eslint-plugin-react 1.5.0

**Comment by sebmck** [comment] 2015-04-14 01:06
Can you please verify that this issue still exists on 3.0.1?

**Comment by hzoo** [comment] 2015-05-15 18:49
Is this still an issue after using `eslint-plugin-react`?

**Comment by MoOx** [comment] 2015-05-15 18:55
Not at all. You can close this. Eslint doesn't handle this anymore & the plugin does this like a charm.

**Comment by hzoo** [comment] 2015-05-15 18:56
Ok great!

**Closed by hzoo** 2015-05-15 18:56 UTC

**Comment by CatzillaOrz** [comment] 2017-11-24 04:03
From [eslint docs](https://eslint.org/docs/rules/no-undef) we can find these rules, 

> Disallow Undeclared Variables (no-undef)
>Any reference to an undeclared variable causes a warning, unless the variable is explicitly mentioned in a /*global ...*/ comment.

```javascript
/*global someFunction b:true*/
/*eslint no-undef: "error"*/

var a = someFunction();
b = 10;
```
