### ISSUE TITLE
v10.0.0: TypeError: Cannot read property 'range' of null

### ISSUE THREAD

**Issue by johngeorgewright** [babel/babel-eslint#695] opened 2018-09-26 09:04 UTC
Just tried updating my version of babel-eslint to `v10`(using eslint `v5.6`) and received an error of which I'm unsure how to get around.

```
Cannot read property 'range' of null
TypeError: Cannot read property 'range' of null
    at SourceCode.getTokenBefore (...node_modules/eslint/lib/token-store/index.js:303:18)
    at checkFunction (...node_modules/eslint/lib/rules/space-before-function-paren.js:117:42)
    at listeners.(anonymous function).forEach.listener (...node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (...node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (...node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (...node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (...node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (...node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)
    at nodeQueue.forEach.traversalInfo (...node_modules/eslint/lib/linter.js:860:28)
```

My eslint config:

```js
module.exports = {
  extends: [
    'plugin:flowtype/recommended',
    'standard'
  ],
  parser: 'babel-eslint',
  plugins: [
    'flowtype'
  ]
}
```

**Comment by hzoo** [comment] 2018-09-26 19:32
I believe this is the same issue as https://github.com/babel/babel-eslint/issues/691 so just going to merge this into that one.

Duplicate of https://github.com/babel/babel-eslint/issues/691

**Closed by hzoo** 2018-09-26 19:32 UTC
